// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Queue.Infrastructure.Persistence;

#nullable disable

namespace Queue.Infrastructure.Migrations
{
    [DbContext(typeof(QueueDbContext))]
    [Migration("20260422044934_InitialFullSchema")]
    partial class InitialFullSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingService", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("BookingId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("BookingServices", (string)null);
                });

            modelBuilder.Entity("CustomerTagMap", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("CustomerTagMaps", (string)null);
                });

            modelBuilder.Entity("Queue.Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("HouseNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SubdistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("SubdistrictId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Queue.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int?>("QueueCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("QueueNumber")
                        .HasColumnType("int");

                    b.Property<int>("QueueSlotId")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ShopId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Guid" }, "IX_Bookings_Guid")
                        .IsUnique();

                    b.HasIndex(new[] { "QueueCategoryId" }, "IX_Bookings_QueueCategoryId");

                    b.HasIndex(new[] { "QueueNumber" }, "IX_Bookings_QueueNumber");

                    b.HasIndex(new[] { "QueueSlotId" }, "IX_Bookings_QueueSlotId");

                    b.HasIndex(new[] { "StatusId" }, "IX_Bookings_StatusId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Guid" }, "IX_Customers_Guid")
                        .IsUnique();

                    b.HasIndex(new[] { "ShopId" }, "IX_Customers_ShopId");

                    b.HasIndex(new[] { "UserId", "ShopId" }, "IX_Customers_UserId_ShopId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Queue.Domain.Entities.CustomerNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerNotes");
                });

            modelBuilder.Entity("Queue.Domain.Entities.CustomerTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CustomerTags");
                });

            modelBuilder.Entity("Queue.Domain.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameTh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("Queue.Domain.Entities.EmailConfirmation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Token" }, "IX_EmailConfirmations_Token");

                    b.HasIndex(new[] { "TokenHash" }, "IX_EmailConfirmations_TokenHash");

                    b.HasIndex(new[] { "UserId" }, "IX_EmailConfirmations_UserId");

                    b.ToTable("EmailConfirmations");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.HasIndex("StatusId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Queue.Domain.Entities.MasterStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameTh")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Type", "Code" }, "IX_MasterStatuses_Type_Code")
                        .IsUnique();

                    b.ToTable("MasterStatuses");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Queue.Domain.Entities.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("StatusId");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("StatusId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Queue.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionRef")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameTh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Queue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("QueueNumber")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex(new[] { "Guid" }, "IX_Queues_Guid")
                        .IsUnique();

                    b.HasIndex(new[] { "ShopId" }, "IX_Queues_ShopId");

                    b.HasIndex(new[] { "StatusId" }, "IX_Queues_StatusId");

                    b.ToTable("Queues");
                });

            modelBuilder.Entity("Queue.Domain.Entities.QueueCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("QueueCategories");
                });

            modelBuilder.Entity("Queue.Domain.Entities.QueueLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QueueId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("QueueId");

                    b.HasIndex("StatusId");

                    b.ToTable("QueueLogs");
                });

            modelBuilder.Entity("Queue.Domain.Entities.QueueSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentUsage")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("MaxQueue")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.HasIndex(new[] { "BranchId", "Date", "StartTime" }, "IX_QueueSlots_Branch_Date_StartTime")
                        .IsUnique();

                    b.HasIndex(new[] { "Guid" }, "IX_QueueSlots_Guid")
                        .IsUnique();

                    b.ToTable("QueueSlots");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.HasIndex(new[] { "Guid" }, "IX_Services_Guid")
                        .IsUnique();

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Queue.Domain.Entities.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("ServiceCategories");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "Guid" }, "IX_Shops_Guid")
                        .IsUnique();

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("Queue.Domain.Entities.ShopBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ShopId");

                    b.HasIndex(new[] { "Guid" }, "IX_ShopBranches_Guid")
                        .IsUnique();

                    b.ToTable("ShopBranches");
                });

            modelBuilder.Entity("Queue.Domain.Entities.ShopBusinessHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("ShopBusinessHours");
                });

            modelBuilder.Entity("Queue.Domain.Entities.ShopHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("HolidayDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("ShopHolidays");
                });

            modelBuilder.Entity("Queue.Domain.Entities.ShopSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("ShopSettings");
                });

            modelBuilder.Entity("Queue.Domain.Entities.ShopStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ShopId", "UserId" }, "IX_ShopStaffs_ShopId_UserId")
                        .IsUnique();

                    b.ToTable("ShopStaffs");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Subdistrict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameTh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Subdistricts");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Queue.Domain.Entities.SystemConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("SystemConfigs");
                });

            modelBuilder.Entity("Queue.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_Users_Email");

                    b.HasIndex(new[] { "Guid" }, "IX_Users_Guid")
                        .IsUnique();

                    b.HasIndex(new[] { "StatusId" }, "IX_Users_StatusId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Queue.Domain.Entities.UserAuthentication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_UserAuthentications_UserId");

                    b.ToTable("UserAuthentications");
                });

            modelBuilder.Entity("Queue.Domain.Entities.UserImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "IsPrimary" }, "IX_UserImages_UserId_IsPrimary");

                    b.ToTable("UserImages");
                });

            modelBuilder.Entity("Queue.Domain.Entities.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("RefreshSalt")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Session")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Guid" }, "IX_UserSessions_Guid")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "IX_UserSessions_UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("ServiceCategoryMap", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ServiceId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ServiceCategoryMaps", (string)null);
                });

            modelBuilder.Entity("ServiceStaffMap", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("ServiceId", "StaffId");

                    b.HasIndex("StaffId");

                    b.ToTable("ServiceStaffMaps", (string)null);
                });

            modelBuilder.Entity("UserRoleMap", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_UserRoleMaps_RoleId");

                    b.ToTable("UserRoleMaps", (string)null);
                });

            modelBuilder.Entity("BookingService", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_BS_Booking");

                    b.HasOne("Queue.Domain.Entities.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK_BS_Service");
                });

            modelBuilder.Entity("CustomerTagMap", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_CTM_Customer");

                    b.HasOne("Queue.Domain.Entities.CustomerTag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .IsRequired()
                        .HasConstraintName("FK_CTM_Tag");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Address", b =>
                {
                    b.HasOne("Queue.Domain.Entities.District", "District")
                        .WithMany("Addresses")
                        .HasForeignKey("DistrictId")
                        .IsRequired()
                        .HasConstraintName("FK_Addr_Dist");

                    b.HasOne("Queue.Domain.Entities.Province", "Province")
                        .WithMany("Addresses")
                        .HasForeignKey("ProvinceId")
                        .IsRequired()
                        .HasConstraintName("FK_Addr_Prov");

                    b.HasOne("Queue.Domain.Entities.Subdistrict", "Subdistrict")
                        .WithMany("Addresses")
                        .HasForeignKey("SubdistrictId")
                        .IsRequired()
                        .HasConstraintName("FK_Addr_Sub");

                    b.Navigation("District");

                    b.Navigation("Province");

                    b.Navigation("Subdistrict");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Booking", b =>
                {
                    b.HasOne("Queue.Domain.Entities.ShopBranch", "Branch")
                        .WithMany("Bookings")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Branch");

                    b.HasOne("Queue.Domain.Entities.QueueCategory", "QueueCategory")
                        .WithMany("Bookings")
                        .HasForeignKey("QueueCategoryId")
                        .HasConstraintName("FK_Bookings_Category");

                    b.HasOne("Queue.Domain.Entities.QueueSlot", "QueueSlot")
                        .WithMany("Bookings")
                        .HasForeignKey("QueueSlotId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Slot");

                    b.HasOne("Queue.Domain.Entities.Shop", "Shop")
                        .WithMany("Bookings")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Shop");

                    b.HasOne("Queue.Domain.Entities.MasterStatus", "Status")
                        .WithMany("Bookings")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Status");

                    b.HasOne("Queue.Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_User");

                    b.Navigation("Branch");

                    b.Navigation("QueueCategory");

                    b.Navigation("QueueSlot");

                    b.Navigation("Shop");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Shop", "Shop")
                        .WithMany("Customers")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_Customers_Shop");

                    b.HasOne("Queue.Domain.Entities.User", "User")
                        .WithMany("Customers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Customers_User");

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Queue.Domain.Entities.CustomerNote", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Customer", "Customer")
                        .WithMany("CustomerNotes")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_CustomerNotes_Customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Queue.Domain.Entities.District", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .IsRequired()
                        .HasConstraintName("FK_Districts_Provinces");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Queue.Domain.Entities.EmailConfirmation", b =>
                {
                    b.HasOne("Queue.Domain.Entities.User", "User")
                        .WithMany("EmailConfirmations")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_EmailConfirmations_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Shop", "Shop")
                        .WithMany("Invoices")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_Invoices_Shop");

                    b.HasOne("Queue.Domain.Entities.MasterStatus", "Status")
                        .WithMany("Invoices")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Invoices_Status");

                    b.Navigation("Shop");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Queue.Domain.Entities.MasterStatus", "Status")
                        .WithMany("Notifications")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Status");

                    b.HasOne("Queue.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_User");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Queue.Domain.Entities.NotificationLog", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Notification", "Notification")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("NotificationId")
                        .IsRequired()
                        .HasConstraintName("FK_NotificationLogs_Notification");

                    b.HasOne("Queue.Domain.Entities.MasterStatus", "Status")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_NotificationLogs_Status");

                    b.Navigation("Notification");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Booking");

                    b.HasOne("Queue.Domain.Entities.MasterStatus", "Status")
                        .WithMany("Payments")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Status");

                    b.Navigation("Booking");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Queue.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Payment", "Payment")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("PaymentId")
                        .IsRequired()
                        .HasConstraintName("FK_PaymentTransactions_Payment");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Queue", b =>
                {
                    b.HasOne("Queue.Domain.Entities.ShopBranch", "Branch")
                        .WithMany("Queues")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_Queues_Branch");

                    b.HasOne("Queue.Domain.Entities.Shop", "Shop")
                        .WithMany("Queues")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_Queues_Shop");

                    b.HasOne("Queue.Domain.Entities.MasterStatus", "Status")
                        .WithMany("Queues")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Queues_Status");

                    b.Navigation("Branch");

                    b.Navigation("Shop");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Queue.Domain.Entities.QueueCategory", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Shop", "Shop")
                        .WithMany("QueueCategories")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_QC_Shop");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Queue.Domain.Entities.QueueLog", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Queue", "Queue")
                        .WithMany("QueueLogs")
                        .HasForeignKey("QueueId")
                        .IsRequired()
                        .HasConstraintName("FK_QueueLogs_Queue");

                    b.HasOne("Queue.Domain.Entities.MasterStatus", "Status")
                        .WithMany("QueueLogs")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_QueueLogs_Status");

                    b.Navigation("Queue");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Queue.Domain.Entities.QueueSlot", b =>
                {
                    b.HasOne("Queue.Domain.Entities.ShopBranch", "Branch")
                        .WithMany("QueueSlots")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_QS_Branch");

                    b.HasOne("Queue.Domain.Entities.Shop", "Shop")
                        .WithMany("QueueSlots")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_QS_Shop");

                    b.Navigation("Branch");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Service", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Shop", "Shop")
                        .WithMany("Services")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_Services_Shop");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Queue.Domain.Entities.ServiceCategory", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Shop", "Shop")
                        .WithMany("ServiceCategories")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_SC_Shop");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Shop", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Address", "Address")
                        .WithMany("Shops")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("FK_Shops_Address");

                    b.HasOne("Queue.Domain.Entities.User", "Owner")
                        .WithMany("Shops")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_Shops_User");

                    b.HasOne("Queue.Domain.Entities.MasterStatus", "Status")
                        .WithMany("Shops")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Shops_Status");

                    b.Navigation("Address");

                    b.Navigation("Owner");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Queue.Domain.Entities.ShopBranch", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Address", "Address")
                        .WithMany("ShopBranches")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("FK_SB_Address");

                    b.HasOne("Queue.Domain.Entities.Shop", "Shop")
                        .WithMany("ShopBranches")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_SB_Shop");

                    b.Navigation("Address");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Queue.Domain.Entities.ShopBusinessHour", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Shop", "Shop")
                        .WithMany("ShopBusinessHours")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_ShopBusinessHours_Shop");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Queue.Domain.Entities.ShopHoliday", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Shop", "Shop")
                        .WithMany("ShopHolidays")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_Holidays_Shop");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Queue.Domain.Entities.ShopSetting", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Shop", "Shop")
                        .WithMany("ShopSettings")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_ShopSettings_Shop");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Queue.Domain.Entities.ShopStaff", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Shop", "Shop")
                        .WithMany("ShopStaffs")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_SS_Shop");

                    b.HasOne("Queue.Domain.Entities.User", "User")
                        .WithMany("ShopStaffs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_SS_User");

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Subdistrict", b =>
                {
                    b.HasOne("Queue.Domain.Entities.District", "District")
                        .WithMany("Subdistricts")
                        .HasForeignKey("DistrictId")
                        .IsRequired()
                        .HasConstraintName("FK_Subdistricts_Districts");

                    b.Navigation("District");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Shop", "Shop")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_Subscriptions_Shop");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Queue.Domain.Entities.User", b =>
                {
                    b.HasOne("Queue.Domain.Entities.MasterStatus", "Status")
                        .WithMany("Users")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Status");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Queue.Domain.Entities.UserAuthentication", b =>
                {
                    b.HasOne("Queue.Domain.Entities.User", "User")
                        .WithMany("UserAuthentications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserAuth_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Queue.Domain.Entities.UserImage", b =>
                {
                    b.HasOne("Queue.Domain.Entities.User", "User")
                        .WithMany("UserImages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserImages_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Queue.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("Queue.Domain.Entities.User", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserSessions_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServiceCategoryMap", b =>
                {
                    b.HasOne("Queue.Domain.Entities.ServiceCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_SCM_Category");

                    b.HasOne("Queue.Domain.Entities.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK_SCM_Service");
                });

            modelBuilder.Entity("ServiceStaffMap", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK_SSM_Service");

                    b.HasOne("Queue.Domain.Entities.ShopStaff", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_SSM_Staff");
                });

            modelBuilder.Entity("UserRoleMap", b =>
                {
                    b.HasOne("Queue.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_URM_Role");

                    b.HasOne("Queue.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_URM_User");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Address", b =>
                {
                    b.Navigation("ShopBranches");

                    b.Navigation("Shops");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Customer", b =>
                {
                    b.Navigation("CustomerNotes");
                });

            modelBuilder.Entity("Queue.Domain.Entities.District", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Subdistricts");
                });

            modelBuilder.Entity("Queue.Domain.Entities.MasterStatus", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Invoices");

                    b.Navigation("NotificationLogs");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("QueueLogs");

                    b.Navigation("Queues");

                    b.Navigation("Shops");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Notification", b =>
                {
                    b.Navigation("NotificationLogs");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Payment", b =>
                {
                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Province", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Districts");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Queue", b =>
                {
                    b.Navigation("QueueLogs");
                });

            modelBuilder.Entity("Queue.Domain.Entities.QueueCategory", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Queue.Domain.Entities.QueueSlot", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Shop", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Customers");

                    b.Navigation("Invoices");

                    b.Navigation("QueueCategories");

                    b.Navigation("QueueSlots");

                    b.Navigation("Queues");

                    b.Navigation("ServiceCategories");

                    b.Navigation("Services");

                    b.Navigation("ShopBranches");

                    b.Navigation("ShopBusinessHours");

                    b.Navigation("ShopHolidays");

                    b.Navigation("ShopSettings");

                    b.Navigation("ShopStaffs");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Queue.Domain.Entities.ShopBranch", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("QueueSlots");

                    b.Navigation("Queues");
                });

            modelBuilder.Entity("Queue.Domain.Entities.Subdistrict", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Queue.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Customers");

                    b.Navigation("EmailConfirmations");

                    b.Navigation("Notifications");

                    b.Navigation("ShopStaffs");

                    b.Navigation("Shops");

                    b.Navigation("UserAuthentications");

                    b.Navigation("UserImages");

                    b.Navigation("UserSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
